#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_PROPERTIES)	+= of_touchscreen.o
obj-$(CONFIG_TOUCHSCREEN_NT36xxx)	+= NVT_Touch/
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_v27) += synaptics_dsx_2.7/
